#!/bin/bash
#
# File promise for KNAF
#
# (C) 2015 Mike Baehr
#
# This is free software: see COPYING for terms/conditions

action=$1
file=/$2
trait=$3
value=$4

[ -e "$file" ] || exit 1

case $trait in
  mode)
    case $0 in
      *linuxfile)
        mode=`stat -c %a "$file"`
        ;;
      *darwinfile)
        mode=`stat -f %Op "$file"|cut -c 4-`
        ;;
      *)
        exit 1
        ;;
    esac
    if [ $mode -eq $value ]; then
      true
    else
      case $action in
        verify)
          false
          ;;
        enforce)
          chmod $value "$file"
          ;;
      esac
    fi
    ;;
esac
