#!/bin/bash
#
# File promise for KNAF
#
# (C) 2015 Mike Baehr
#
# This is free software: see COPYING for terms/conditions

action=$1
file=/$2
trait=$3
value=$4

[ -e "$file" ] || exit 1

# Should probably make this happen
# automatically by sourcing facter

while IFS=':' read -a fact; do
  eval ${fact[0]}\=${fact[1]}
done < <(facter)

case $trait in
  mode)
    case $os in
      Linux)
        mode=`stat -c %a "$file"`
        ;;
      Darwin)
        mode=`stat -f %Op "$file"|cut -c 4-`
        ;;
      *)
        exit 1
        ;;
    esac
    if [ $mode -eq $value ]; then
      true
    else
      case $action in
        verify)
          false
          ;;
        enforce)
          chmod $value "$file" && true || false
          ;;
      esac
    fi
    ;;
esac
